spring.application.name=meu-salao-digital-api

spring.datasource.url=${URL_BASE}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}

spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=465

spring.mail.username=${EMAIL}
spring.mail.password=${EMAIL_PASSWORD}

resend.api.key=${RESEND_API_KEY}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=60000
spring.mail.properties.mail.smtp.timeout=60000
spring.mail.properties.mail.smtp.writetimeout=60000